In [1]:
#!/usr/bin/env python

# Train a 4-layer neural network
import math
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from keras import optimizers
from keras.models import Sequential
from keras.layers import Dense, Flatten

Using TensorFlow backend.


In [2]:
def train_model(X_train, Y_train, X_dev, Y_dev, learning_rate=0.0001, num_epochs=100, batch_size=32, print_cost=True):
    # Define model
    model = Sequential()
    model.add(Flatten())
    model.add(Dense(256, activation='relu'))
    model.add(Dense(1024, activation='relu'))
    model.add(Dense(256, activation='relu'))
    model.add(Dense(64, activation='sigmoid'))
    
    # Compile and train
    model.compile(optimizer=optimizers.SGD(lr=learning_rate), loss='binary_crossentropy', metrics=['accuracy'])
    history = model.fit(X_train, Y_train, validation_data=(X_dev, Y_dev), epochs=num_epochs, batch_size=batch_size)
    
    return model, history

In [6]:
# Load full data
print('Loading data...')
train_x = np.moveaxis(np.load('/data/loop_detector/train_X.npy'), -1, 0)
train_y = np.moveaxis(np.load('/data/loop_detector/train_Y.npy'), -1, 0)
dev_x = np.moveaxis(np.load('/data/loop_detector/dev_X.npy'), -1, 0)
dev_y = np.moveaxis(np.load('/data/loop_detector/dev_Y.npy'), -1, 0)
test_x = np.moveaxis(np.load('/data/loop_detector/test_X.npy'), -1, 0)
test_y = np.moveaxis(np.load('/data/loop_detector/test_Y.npy'), -1, 0)

trainx = np.expand_dims(train_x, axis=-1)
trainy = np.reshape(train_y, (train_y.shape[0], train_y.shape[1]))
devx = np.expand_dims(dev_x, axis=-1)
devy = np.reshape(dev_y, (dev_y.shape[0], dev_y.shape[1]))
testx = np.expand_dims(test_x, axis=-1)
testy = np.reshape(test_y, (test_y.shape[0], test_y.shape[1]))
print(trainx.shape)
print(devy.shape)
print('Data loaded...')

Loading data...
(178800, 64, 64, 1)
(22350, 64)
Data loaded...


In [7]:
# Train model
print('Beginning training...')
# trainx = trainx[:2]
# trainy = trainy[:2]
lr = 0.001
nepochs = 10
mbsize = 32
model, history = train_model(trainx, trainy, devx, devy, learning_rate=lr, num_epochs=nepochs, batch_size=mbsize)

Beginning training...
Train on 178800 samples, validate on 22350 samples
Epoch 1/10
178800/178800 [==============================] - 68s 383us/step - loss: 0.6660 - acc: 0.6154 - val_loss: 0.6329 - val_acc: 0.6494
Epoch 2/10
178800/178800 [==============================] - 68s 380us/step - loss: 0.6174 - acc: 0.6671 - val_loss: 0.6079 - val_acc: 0.6782
Epoch 3/10
178800/178800 [==============================] - 69s 387us/step - loss: 0.5953 - acc: 0.6896 - val_loss: 0.5929 - val_acc: 0.6913
Epoch 4/10
178800/178800 [==============================] - 68s 381us/step - loss: 0.5809 - acc: 0.7023 - val_loss: 0.5761 - val_acc: 0.7057
Epoch 5/10
178800/178800 [==============================] - 69s 385us/step - loss: 0.5706 - acc: 0.7103 - val_loss: 0.5675 - val_acc: 0.7129
Epoch 6/10
178800/178800 [==============================] - 68s 381us/step - loss: 0.5624 - acc: 0.7162 - val_loss: 0.5583 - val_acc: 0.7188
Epoch 7/10
178800/178800 [==============================] - 69s 384us/step - loss

In [10]:
# Error analysis

my_model = model
x = trainx
y = trainy

i = np.random.choice(range(x.shape[0]))
print(str(i) + 'th example')
pred = np.round(my_model.predict(x[i].reshape(1,64,64,1)).reshape(64,1))
label = y[i].reshape(64,1)
results = np.concatenate((pred, label, (pred-label)*99), axis=1)
print('Pred True Correct')
print(results)

70638th example
Pred True Correct
[[  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  1.   1.   0.]
 [  1.   1.   0.]
 [  1.   1.   0.]
 [  1.   1.   0.]
 [  1.   0.  99.]
 [  0.   0.   0.]
 [  0.   1. -99.]
 [  0.   1. -99.]
 [  1.   1.   0.]
 [  0.   1. -99.]
 [  1.   1.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  1.   0.  99.]
 [  1.   0.  99.]
 [  1.   1.   0.]
 [  1.   1.   0.]
 [  1.   0.  99.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   1. -99.]
 [  0.   1. -99.]
 [  1.   1.   0.]
 [  1.   1.   0.]
 [  1.   1.   0.]
 [  1.   1.   0.]
 [  1.   1.   0.]
 [  0.   1. -99.]
 [  0.   1. -99.]
 [  0.   1. -99.]
 [  0.   1. -99.]
 [  0.   1. -99.]
 [  0.   0.   0.]
 [  1.   0.  99.]
 [  1.   1.   0.]
 [  1.   1.   0.]
 [  1.   1.   0.]
 [  1.   1.   0.]
 [  0.   1. -99.]
 [  0.   0.   0.]
 [  1.   0.  99.]
 [  1.   0. 

In [11]:
# Save model
import pickle
model.save('model256102425664_lr{}_epochs{}_mbsize12{}.h5'.format(lr, nepochs, mbsize))
with open('history256102425664_lr{}_epochs{}_mbsize12{}.pkl'.format(lr, nepochs, mbsize), 'wb') as f:
    pickle.dump(history.history, f, pickle.HIGHEST_PROTOCOL)
